version: '3.5'

services:
  db:
    image: postgres
    restart: always
    env_file:
      - .env
    container_name: postgres
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=pgadmin4@pgamin.org
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:  
      - "5050:80"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: express-docker-postgres
    environment:
      - PORT=${PORT}
      - NODE_ENV=development
    ports:
      - '3000:3000'
    depends_on:
      - db
    restart: on-failure:10
    volumes:
      - ./src:/app/src  